name: Publish Nightly Docker Image
on:
  push:
    paths-ignore:
      - '.github/*.yml'
      - '*.md'
      - '.*'
      - 'LICENSE'
      - 'Guardfile'
    branches:
      - develop
jobs:
  push_to_registry:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@master
    - name: Get build date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S %z')"
    - name: Publish to Github Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        REPLACE_CHINA_MIRROR: false
        VCS_REF: ${{ github.sha }}
        BUILD_DATE: ${{ steps.date.outputs.date }}
        TAG: nightly
      with:
        name: ghcr.io/tryzealot/zealot:${{ env.TAG }}
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
        buildargs: BUILD_DATE,VCS_REF,TAG,REPLACE_CHINA_MIRROR
        registry: ghcr.io
    - name: Publish to Docker Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        REPLACE_CHINA_MIRROR: false
        VCS_REF: ${{ github.sha }}
        BUILD_DATE: ${{ steps.date.outputs.date }}
        TAG: nightly
      with:
        name: tryzealot/zealot:${{ env.TAG }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: BUILD_DATE,VCS_REF,TAG,REPLACE_CHINA_MIRROR
    - name: Update Docker Hub Description
      uses: peter-evans/dockerhub-description@v2.1.0
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: tryzealot/zealot